### PR TITLE
Added custom toasts

### PR DESCRIPTION
**Pull request by flick36**
The toasts, as the Dialogs can have a custom template, and also they can receive a promise, so they've should have optional params too see [example](https://material.angularjs.org/latest/demo/toast)

### CODE REVIEW

**Comment by jadjoubran** [comment]
Thanks for your efforts @flick36 
Unfortunately I think that's too much to be included out of the box..
Custom toasts aren't that frequent.. and where you might need to use a custom toast, I don't think you'd need to use more than 1 (in most scenario)
Same for this PR jadjoubran/laravel-ng-artisan-generators#29

**Comment by shiruken1** [comment]
@flick36 I was _just_ looking for this feature! Thank you so much! :+1: :smile:

**Comment by flick36** [comment]
@shiruken1 sure man, no problem.
@jadjoubran but maybe the `.less` file on dialogs you can do?

**Comment by jadjoubran** [comment]
Yeah generating less files on a dialog would work if you want 👍

**Pull request closed without merging**
