### PR TITLE
Update API.service.js

### PR DESCRIPTION
**Pull request by santiagogg**
This resolves issue #135

### CODE REVIEW

**Comment by shiruken1** [comment]
@santiagogg Oh, hey! Thanks for that :smile:

**Comment by jadjoubran** [comment]
Hi @santiagogg 
Thanks for this!

Would you please be able to explain how this would be useful? as I've never used the `getList` before
If you can just provide us with an example or so

**Comment by santiagogg** [comment]
It's seems like Dingo is handling the response and when the controller return an eloquent collection the json is encapsulating the array as in this example:

```
{
errors: false,
data: {
afiliados: [
{
id: "1",
nombre: "Mr. Oren Lemke",
nro_afiliado: "1685"
},
...
]
}
```

With that fix on the angular API service we are telling to restangular where to get the array.

Hope this helps!

and thanks for this repo :)

**Comment by jadjoubran** [comment]
@santiagogg oh.. I guess that's the response macro
yes sounds great!

I just need to pull this in and run a quick tests
I'll try to merge this by tomorrow as I'm swamped with work

Thanks a lot!

**Comment by santiagogg** [comment]
:+1:  Thanks @jadjoubran

**Comment by shiruken1** [comment]
@jadjoubran Speaking of APIs... did my comment regarding passing the domain param to Dingo in the routes.php file make sense?

Otherwise, the authentication middleware would not work for me.

**Comment by santiagogg** [comment]
I would prefer avoid using dingo in the future. Laravel is making all that dingo provide really easy.

**Comment by jadjoubran** [comment]
Hi @santiagogg 
I pulled your branch and tried to make it work with a getList operation.. it actually breaks if you return an array from the backend..
Would you please be able to cater for this scenario?

Also it would be great if you can use the same variables presented in restangular's documentation (it'll make it much easier for other people to tinker with)
`RestangularProvider.addResponseInterceptor(function(data, operation, what, url, response, deferred) {`

So Laravel 5.2 has some of these features? I believe you're talking about the 5.2 Auth features.. Feel free to open a new issue so we can further discuss this!

@shiruken1 Do you have `API_PREFIX=api` in your `.env` file?

**Comment by jadjoubran** [comment]
Hi @santiagogg 
Any update on this?
I'd love to merge this before 3.1 since this might be breaking for some people and 3.1 would be a great time to document this

**Comment by santiagogg** [comment]
Hi @jadjoubran, I didn't have time for this. 
I'll have a look tomorrow.

**Comment by shiruken1** [comment]
I'll give this a shot once I get to where I'm flying to.

**Comment by shiruken1** [comment]
Hello, again! I tested this mod and it doesn't work for me either. It insists "respose.data" is undefined.

Sorry I didn't answer your question earlier, @jadjoubran, but yes. I have "API_PREFIX=api" in my .env, but even still, Dingo won't work without the 'domain'=>'localhost' (or whatever's appropriate) in my routes.php

**Comment by jadjoubran** [comment]
@santiagogg I have to close this for inactivity..
Feel free to submit a fix for it as a new PR
Thank you!

**Pull request closed without merging**
