### PR TITLE
Fixes issues #356 and #358

### PR DESCRIPTION
**Pull request by chihab**
**What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
- [x] Bugfix
- [x] Build related changes
- [x] CI related changes

**What is the current behavior?** (You can also link to an open issue here)
Issues #356 and #358 

**What is the new behavior?**
No more composer create-project (from stable branch). CI runs on cloned repo.

**Does this PR introduce a breaking change?**
- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by chihab** [comment]
@jadjoubran just realized that I made the PR on master branch which is not the stable branch that composer fetches with composer create-project command. The fix won't apply to 3.2.1 then. Either a partial merge has to be done on the stable branch or maybe should I submit two differents PRs, one for the travis issue and one for the require css issue.

**Comment by jadjoubran** [comment]
hmm travis needs to be fixed on both anyway no?
So I think I can merge this one now and then we can target another one for 3.2.1
Let me know

**Comment by chihab** [comment]
Yes, Travis issue has to be fixed on both.
The other issue is related to pwa only.

By the way, how do you tell composer which branch to target with a composer create-project ? Is it the default branch/tag on github that you set on project settings ?

**Comment by jadjoubran** [comment]
yeah by default it downloads the latest stable tagged version

**Pull request merged**
