### PR TITLE
Fix travis build

### PR DESCRIPTION
**Pull request by jadsalhani**

### CODE REVIEW

**Comment by jadsalhani** [comment]
@jadjoubran `Take 5` fixed it, the error on it is with a Test not node itself. I guess bumping the version to `5.1` fixed the issue

**Comment by jadsalhani** [comment]
Turns out `testLandingResponseCode` test was failing because we were missing the `gulp` command to compile the templates/scripts/files and create the `public/build` to actually correctly return the landing template

Adding it fixed
Maybe we should squash the commits when merging this one for the sake of saving 5 commit messages

**Comment by jadjoubran** [comment]
Still failing sometimes.. seems like a race condition because it's not always giving the same results
The new issue seems to be with phantomjs

**Comment by jadsalhani** [comment]
I think there was a problem with github at the time of the build, because the get request of phantom was 403... I guess we can trigger it one more time to be sure

**Pull request merged**
