### PR TITLE
Added redirect to state after login

### PR DESCRIPTION
**Pull request by flick36**
A better way to redirect the user after they log in, they will be redirected to the state they attempt to visit, or to the landing page (you decide wich state in the code).

A better and best way to do #282

### CODE REVIEW

**Comment by jadjoubran** [comment]
Hi @flick36 
Thanks for your efforts! But unfortunately this is too opinionated to be available out of the box.. Some people wouldn't need it, they can just add `this.$state.go` call after the toast..

**Comment by odyright** [comment]
hi, good in most case it would be useful!

**Comment by jadjoubran** [comment]
@odyright Thanks for your feedback!
Isn't it easier to just write the below?

``` javascript
this.$state.go('name');
```

**Comment by flick36** [comment]
I found it useful for example when the token expired, and if your user was navigating, to let's say a route

`localhost:3000/#/routeone/1/subroute/1/details`

you are gonna redirect him to the initials state, instead of just sending him back to where he was .-.

also if your user has a bookmark to any page he needs the most in your app, he would access it trough it, gonna get asked for the login and redirects him to wherever he wants to be redirect to , and if he has the permissions of course

**Comment by shiruken1** [comment]
I second the opinion that this would be very useful, @jadjoubran. Thanks, @flick36!

Perhaps this could be a recipe?

**Comment by jadjoubran** [comment]
Thanks again @flick36, indeed it looks useful in some scenarios so as @shiruken1 let's keep it as a recipe.. I'll update #149

**Pull request closed without merging**
