### PR TITLE
Return all exceptions thrown using the error response macro

### PR DESCRIPTION
**Pull request by shiruken1**
Don't know if I missed something in the docs/code, but this **really** saves me work while debugging.

Let me know if I did!

### CODE REVIEW

**Comment by jadjoubran** [comment]
hmmm nice!
Could you please show me an example of the response message that can be returned?
Btw for debugging you can add API_DEBUG=true to your `.env` file

**Comment by shiruken1** [comment]
Hmm... I seem to have missed something. I copy pasted code from a previously successful mod without checking it. Sorry about that!

Remind me, again, how do I push changes to an already-open PR? Thanks, and my apologies once again.

**Comment by jadjoubran** [comment]
No worries
Just push to the same branch and it should update automatically

**Comment by shiruken1** [comment]
Bah. Totally jumped the gun on that one. Dingo API intercepts the Exception before handler.php even sees it.

Sorry for the trouble!

**Comment by shiruken1** [comment]
BTW. I do have API_DEBUG set to true. Is there any other way to see any exceptions thrown, other than going through the Network tab in the dev console?

**Comment by jadjoubran** [comment]
No worries!

Open the API.service.js.. you can setup a toast notification maybe or a $log for when the response code is 500

**Comment by shiruken1** [comment]
Now why didn't I think of that!?

Oh yeah, because I usually over complicate things... :sad:

Thank you so much!

**Comment by jadjoubran** [comment]
Good luck! :smile:

**Pull request closed without merging**
