### PR TITLE
fix #421

### LINKED ISSUE #421: Should return 404 not 500
- **I'm submitting a ...**
- [x] bug report
- [ ] feature request
- [ ] support request
- [ ] other (Please specify)
- **Provide information & explanation**
  Hi, on [Handler.php#L49](https://github.com/jadjoubran/laravel5-angular-material-starter/blob/master/app/Exceptions/Handler.php#L49) and [#65](https://github.com/jadjoubran/laravel5-angular-material-starter/blob/master/app/Exceptions/Handler.php#L65)

``` php
Route::current();
```

returns null on invalid route, so it will call getPrefix() on null that throws 500 instead 404.
also, what if the api has no prefix, but subdomain based api?

I think it should check for the middlewares existance, like follows (You can do it better than me)

``` php

    /**
     * Check for api routes.
     *
     * @param Request $request
     * @return bool
     */
    protected function isApiRoute($request)
    {
        return $request->route() && in_array('api', (array) $request->route()->middleware());
    }
```
- **Laravel & Angular version:** 3.4.0

### PR DESCRIPTION
**Pull request by ghost**
**What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**Does this PR introduce a breaking change?**
- [ ] Yes
- [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Comment by nueko** [comment]
this is not fixed yet as there's such snippet on Controller.php

**Comment by jadjoubran** [comment]
Thanks @nueko for this!
Actually why not keep it as `wantsJson()` only?
Do you see any downside with this?

**Comment by nueko** [comment]
I tested it with make:auth scaffolding as it use ThrottlesLogin and it uses web middleware,
but, I think we better use expectsJson for that,

**Comment by jadjoubran** [comment]
Okay, thanks for this @nueko 
I'll pull the branch and run some quick tests and get back to you
Thanks! 😄

**Comment by jadjoubran** [comment]
Looks great, thanks!

**Pull request merged**
