### PR TITLE
Applied fixes from StyleCI

### PR DESCRIPTION
**Pull request by jadjoubran**
This pull request applies code style fixes from an analysis carried out by [StyleCI](https://styleci.io).

---

For more information, click [here](https://styleci.io/analyses/zOd6a8).

### CODE REVIEW

**Comment by jadjoubran** [comment]
@GrahamCampbell Are you sure it's a good idea to remove the imports on the controller?
I spent 10 minutes wondering why my `Request` dependency injection wasn't working..

**Comment by GrahamCampbell** [comment]
Yeh, this looks fine.

**Comment by GrahamCampbell** [comment]
All those imports are unused.

**Comment by GrahamCampbell** [comment]
And App\Http\Controllers\Controller isn't needed because it's already in the same namespace.

**Pull request merged**
