### PR TITLE
Update .gitignore

### PR DESCRIPTION
**Pull request by ghost**
**What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**Does this PR introduce a breaking change?**
- [ ] Yes
- [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

ignore .idea/

### CODE REVIEW

**Comment by flick36** [comment]
Ummm. there's no file/folder with that name, it's generated by the IDE Intellijd or phpstorm or similar... wich not everyone uses... so i don't see the point on merging this

**Comment by nueko** [comment]
Yea, that's just for users who use the IDE.

**Comment by GrahamCampbell** [comment]
👎

**Comment by GrahamCampbell** [comment]
This file belongs in global .gitignore files since it's system specific.

**Comment by jadjoubran** [comment]
Yeah I actually learned that from @GrahamCampbell a few years ago 😄 
All IDE/OS specific ignores should go into the global gitignore

**Pull request closed without merging**
