### PR TITLE
Create .bowerrc for gulp work properly

### PR DESCRIPTION
**Pull request by rodrigowaters**
**What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
- [X] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)
$ gulp
$ Using gulpfile /var/www/html/laravel/gulpfile.js
$ Starting 'all'...
$ Starting 'bower-js'...
$ 'bower-js' errored after 2.11 ms
$ Error: Bower components directory does not exist at /var/www/html/laravel/bower_components

**What is the new behavior?**
No error appeared

**Does this PR introduce a breaking change?**
- [ ] Yes
- [X] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Comment by jadjoubran** [comment]
Hi @rodrigowaters 
Thanks for sending this pull request! Have you tried running `bower install` first?
Because normally the error shouldn't exist

**Comment by rodrigowaters** [comment]
Hi @jadjoubran 
Yes, maybe I did something wrong, but this file resolved

**Comment by jadjoubran** [comment]
Alright
Would you be able to run `bower install` without this file though?

**Comment by malylimas** [comment]
@jadjoubran maybe the problem is that the bower install ends with error

this is my log:

ar/bower-angular-aria/archive/v1.6.1.tar.gz
bower angular-messages#^1.4.8                  download https://github.com/angular/bower-angular-messages/archive/v1.6.1.tar.gz
bower angular-animate#^1.4.8                   download https://github.com/angular/bower-angular-animate/archive/v1.6.1.tar.gz
bower lodash#>=1.3.0                           resolved https://github.com/lodash/lodash.git#4.17.4
bower angular-aria#^1.4.8                       extract archive.tar.gz
bower angular-aria#^1.4.8                      resolved https://github.com/angular/bower-angular-aria.git#1.6.1
bower angular-messages#^1.4.8                   extract archive.tar.gz
bower angular-messages#^1.4.8                  resolved https://github.com/angular/bower-angular-messages.git#1.6.1
bower angular-animate#^1.4.8                    extract archive.tar.gz
bower angular-animate#^1.4.8                   resolved https://github.com/angular/bower-angular-animate.git#1.6.1
bower                                         ECONFLICT Unable to find suitable version for angular

**Comment by jadjoubran** [comment]
Hi @malylimas 
Yes you will need to specify a specific version of angular while running bower install
Please try running `bower install` again and answer the `resolution` question
Thanks!

**Pull request closed without merging**
