### PR TITLE
Swapped response number statics for Response constants

### PR DESCRIPTION
**Pull request by shiruken1**
Hello again!

I apologize if this is useless/redundant/just-plain-stupid, but I figured taking the magic numbers out and replacing them with a Response constant would be a tiny contribution I could make to this awesome project.

Also, if putting public/js and public/css in git's ignore list is a bad idea. Feel free to  let me know and I'll remove them from the PR. For whatever reason it was giving me issues, but it wasn't my goal to have it be a part of this PR.

Cheers!

### CODE REVIEW

**Comment by jadjoubran** [comment]
Hi @shiruken1 

Thanks a lot for your contribution, it's actually great!

But can you please go over the [files changed](https://github.com/jadjoubran/laravel5-angular-material-starter/pull/124/files) and fix unnecessary modifications (there's also the artisan file mode change)

And it would be great if you can squash all changes into 1 commit

I'd be happy to assist you with this if you need help

Regarding the .gitignore, you can just manually remove the `map` files for now since we don't want to force everyone to ignore map files.

Cheers!

**Comment by shiruken1** [comment]
Whoops. Making artisan executable is a habit for me at this point. Sorry about that, I'll go ahead and take care of it. Thanks!

**Comment by jadjoubran** [comment]
Btw, did you checkout the new docs? I'd love to get your feedback

**Comment by shiruken1** [comment]
The ones here: https://laravel-angular.readme.io/docs ? If so, yes. They're awesome! Thank you! They got me over the fear I had of TDD :P

Now I'm actually creating the tests I've put off for months on my project. Thanks!

**Comment by jadjoubran** [comment]
Oh that's great news :smile: 
I'm going to start working on screencasts very soon and I'll be focusing a lot on TDD

**Comment by shiruken1** [comment]
Still learning the git ropes, so I'll be closing this PR and opening another one with the single commit.

(Please do let me know if there's a way to not have to do that)

**Comment by jadjoubran** [comment]
@shiruken1 you know I've never done it on a pull request, but that should work I guess

https://davidwalsh.name/squash-commits-git

**Comment by GrahamCampbell** [comment]
> (Please do let me know if there's a way to not have to do that)

No need for a new PR. Just force push while the PR is still open.

**Comment by shiruken1** [comment]
Ah. Well, I'll definitely will take a look at it to learn. Thanks!

**Pull request closed without merging**
